import React, { Component } from 'react'

export default class OnlineWorksCielo extends Component {
  render() {
    return (
 <div class="modal" id="onlineworkscielo" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-full" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Il cielo che prima non c’era - Alessandro Tamburini</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">CHIUDI</span>
                </button>
            </div>
            <div class="modal-body p-4" id="result">
  
				
            “Ti dico che le cose cambieranno! Hanno già cominciato a cambiare” disse Riccardo, fermandosi per dare più peso alle parole. Toni si fermò a sua volta, con la testa incassata fra le spalle e le mani affondate nelle tasche dei pantaloni. <br/>
				“Io non ne sarei così sicuro” ribadì, e con la lingua si fece girare fra i denti un filo d’erba che si era messo in bocca poco prima. <br/>
				“Pensa solo che non c’è più il fascismo! Ti sembra poco?” insistette Riccardo alzando il tono di voce. <br/>
				“Veramente c’è ancora la Repubblica di Salò, e abbiamo i tedeschi in casa…” obbiettò Toni. <br/>
				“Arriveranno gli angloamericani, la guerra l’hanno già vinta, è solo questione di tempo…”. <br/>
				“Sì, ma noi l’abbiamo persa” osservò Toni, e lui si infervorò del tutto, disse “La guerra sarà presto finita, è questo che conta! E tutto potrà ricominciare! Non capisci che cosa significa!?” <br/>
				Toni riprese a camminare e Riccardo gli mollò un gran pugno sulla spalla, in cui scaricò tutto il proprio disappunto. <br/>
				“Testone di un menagramo che non sei altro!” gli disse, e l’altro accusò il colpo, si massaggiò il muscolo del braccio indolenzito. <br/>
				Riccardo aveva a volte di quei moti di insofferenza nei confronti dell’amico. Toni era un ragazzo sveglio, gli piaceva parlare con lui proprio perché aveva sempre un modo suo di guardare le cose, diverso da quello della maggioranza. Però aveva la tendenza a vedere sempre il lato scuro, l’inganno, la fregatura, il verme che bucava anche la mela più bella. E quando prendeva una posizione non c’era più verso di smuoverlo di un millimetro. <br/>
				   Si conoscevano da sempre, da quando portavano i pantaloni corti anche in inverno e condividevano i giochi dell’Oratorio di San Pietro: interminabili partite di pallone d’estate, sul campetto polveroso, e d’inverno calciobalilla, bilie e figurine, con don Ettore che con grandi ceste di brioches li attirava verso la Funzione e combatteva la quotidiana battaglia di dare loro almeno un’infarinatura di religione. A dodici anni avevano avuto in regalo tutti e due una bicicletta ed era stato in quelle lunghe pedalate e sudate che era maturata fra loro un’amicizia esclusiva, che non sarebbe più venuta meno. Poi si erano iscritti allo stesso liceo ed erano cominciate le uscite con le ragazze, con molti impacci e titubanze, seguite da ore di risate e di grande complicità fra loro due, a commentare e riepilogare le prime agognate e per lo più mancate conquiste. Già allora Toni manifestava la sua vena critica, smontando senza pietà i suoi furori romantici, e quel che è peggio più di una volta era capitato che le ragazze preferissero lui, che pure non si innamorava mai di nessuna. <br/>  
				     Riccardo si fermò nel punto in cui il sentiero che avevano percorso si affacciava sul primo slargo asfaltato, alla periferia della città. Rivolse un lungo sguardo ai tetti delle case, col rosso acceso dalla viva luce del mattino, poi prese dalla tasca il tabacco e si arrotolò una sigaretta. Toni fece segno che ne voleva anche lui e Riccardo gli porse il tabacco, mentre accendeva sfregando il fiammifero su un muretto. Poi gli accese la sigaretta con la sua, per non sprecare un secondo fiammifero che era una merce preziosa e diedero insieme le prime avide boccate. 
				Era già da un po’ che avevano quel vizio, che risparmiavano su tutto per raggranellare i soldi necessari a mantenerlo, ma non si azzardavano ancora ad accendere la sigaretta in casa, in presenza dei genitori. Una volta che il padre di Toni lo aveva sorpreso per strada con una in bocca gliel’aveva fatta volare via con uno scappellotto che aveva lasciato il figlio tramortito per mezz’ora. <br/>
				Ma a diciassette anni compiuti erano e si sentivano grandi, specie quando si trovavano da soli, quando si sentivano la propria vita tutta fra le mani. <br/>
				Si erano dati appuntamento quella mattina di domenica, all’ora in cui un tempo andavano a messa, per una delle loro passeggiate fuori città, lungo il sentiero che costeggiava il fiume. Si erano fermati come al solito su un pontile di legno che si staccava dalla riva, nel punto in cui il fiume formava una specie di insenatura, a fumare e a chiacchierare. Prima avevano parlato di ragazze, anche se in quel momento non avevano niente di importante per le mani, ma sulla strada del ritorno i discorsi si erano portati sugli avvenimenti degli ultimi mesi, con le infinite congetture su quando sarebbe finita la guerra e cosa sarebbe accaduto dopo. <br/>
				“Io non credo che finirà tanto presto…” disse Toni, come se nella lunga pausa non si fosse mai staccato da quei pensieri. “L’Italia è lunga e i tedeschi stanno rendendo la vita dura agli Alleati. Dovrà passare almeno un altro inverno, stanne pur certo”. <br/>
				Lui fece il gesto di cacciare via quel tempo come un insetto fastidioso. Disse “Se deve venire un altro inverno, passerà anche quello. Il momento arriverà, e poi niente sarà più come prima!”. <br/>
				Toni scosse la testa. “Cosa ti spetti che succeda? Saranno sempre loro a comandare…” <br/>
				“Loro chi?” <br/>
				“Quelli che hanno comandato sempre, con o senza fascismo, in guerra e in pace: i padroni delle industrie, delle banche, quelli che oggi hanno sulla tavola il pane bianco, la frutta, e sigarette buone a volontà…”. <br/>
				“Non cambierai mai, devi sempre vedere il lato peggiore” sbottò Riccardo. “La guerra finita è un sogno e solo tu non riesci a vederlo. Io dico che faremo festa per un anno intero!”. <br/>
				“Metterà fine a tante sofferenze, questo lo so bene” ammise Toni “ma sarà solo l’inizio, con tutto quel che bisognerà ancora fare dopo”. <br/>
				Erano arrivati all’incrocio che portava in Centro, al caffè dove erano soliti riunirsi la domenica a quell’ora. <br/>
				“La politica verrà quando sarà il suo momento” rispose lui. “Adesso pensiamo a mandare via i tedeschi e poi…”. <br/>
				Gli si spezzarono le parole in bocca perché partì proprio in quel momento l’urlo della sirena, vicinissima visto che si trovavano a pochi isolati dal Comune. <br/>
				Subito i passanti che avevano attorno accelerarono il passo, qualcuno spiccava già la corsa e anche loro cominciarono a muoversi, pur senza ancora dirsi per dove. Toni scrutava il cielo guardando verso sud, mentre con un gesto istintivo lui ritirava il collo fra le spalle, come per ripararsi già dalle bombe. Disse “Da qualche giorno sembrava che ci volessero lasciare in pace”. <br/>
				“Sembrava…” rimarcò Toni, che subito puntò il braccio in direzione delle montagne e un istante dopo nell’azzurro terso del cielo balenò il luccichio di una carlinga, mentre si cominciava a sentire il rombo sordo dei motori. <br/>
				Adesso tutti correvano, in un vocio di grida e richiami che rimbalzavano tra le finestre e la strada. Persiane sbattevano e venivano chiuse, a due passi da loro cadde con gran fragore la serranda di un caffè e li fece sobbalzare come se si trattasse della prima bomba. Si misero a correre anche loro, ancora senza una direzione precisa, quasi saltellando e continuando a guardarsi per prendere in fretta una decisione. <br/>
				“I miei a quest’ora sono tutti a casa e in due minuti arrivano al Rifugio dell’ospedale!” disse Riccardo, col fiatone dell’ansia, più che della corsa. <br/>
				“Idem per i miei” fece l’altro “ma noi non ce la facciamo ad arrivare fin là. E’ molto più vicino il Rifugio di San Martino”. <br/>
				“Allora andiamo lì” disse lui, spiccando per primo una corsa vera e decisa, e subito si voltò per controllare che l’amico gli stesse dietro. <br/>
				Il rombo degli aerei ingigantiva sempre più, sembrava dovesse far precipitare il cielo e Riccardo correva avanti a testa bassa. Sapeva che c’era poco tempo, pochi minuti, forse solo qualche manciata di secondi. Sapeva che i velivoli andavano molto più veloci di lui. <br/>
				Altri correvano dietro e avanti a loro, quasi tutti nella medesima direzione perché il Rifugio di San Martino era meta comune. Lui si disse che sarebbero arrivati in tempo, che ce l’avrebbero fatta come altre volte, anche se ogni volta poteva essere quella che buttava giù la sua casa, o che faceva vittime fra le persone care. Bisognava non pensarci. Bisognava solo correre e sperare che il male fosse il più piccolo e il più lontano possibile. <br/>
				Correvano e divoravano isolati, il Rifugio era ormai a poche centinaia di metri e a Riccardo sembrò di averne già nelle narici il tipico odore di muffa e di terra umida. Ma mentre giravano l’angolo della farmacia di colpo Toni si fermò e lui dovette fare lo stesso, portando una mano alla milza che gli faceva male. <br/> 
				“Dai che manca poco” disse, ma Toni non si era fermato per la stanchezza, gli era venuta in mente di colpo una cosa importante e la disse. “Silvestro è a casa con la caviglia rotta. Lui e sua madre potrebbero aver bisogno!”. <br/>
				Riccardo tirò subito indietro, disse “E cosa vuoi che facciamo noi? Mica possiamo portarlo di peso fino al Rifugio!”. <br/>
				Toni continuava a guardare lui ma aveva cominciato ad arretrare, come se avesse già deciso. <br/>
				“E’ meglio andare a vedere” ribadì. <br/>
				“Lo sai che vanno sempre in cantina! Si arrangeranno così anche stavolta!” provò a insistere lui, ma come c’era da aspettarsi Toni non intendeva recedere dal suo proposito, disse “Siamo lì in due minuti. Poi se mai scendiamo in cantina con loro”. <br/>
				“Due minuti un accidente” ribatté lui, mentre gli saliva dal petto un ansimare più forte di quando stava correndo. “Arrivano prima le bombe! Ti vuoi fare ammazzare! Dammi retta, andiamo al Rifugio!”. <br/>
				“Non importa, vado io solo. Ci ritroviamo quando sarà finito tutto” concluse l’altro, e Riccardo fu attraversato da una specie di vertigine, in cui si mescolavano ansia e orgoglio, fedeltà e paura. Odiava Silvestro e la caviglia che si era rotta stupidamente un paio di settimane prima, e cercava di convincersi che non aveva bisogno del loro aiuto. Una voce gli diceva di non separarsi dall’amico, un’altra di riprendere la corsa verso il Rifugio e lui era come paralizzato, incapace di darsi il comando di scattare nell’una come nell’altra direzione. Ma la voce più forte fu quella del primo lungo fischio, di poco seguito da un boato che esplose ancora distante, ma mandò in pezzi i vetri delle case vicine. E come se avesse troncato di netto la gomena di un ormeggio, mentre Toni ancora esitava come per dargli un’ultima chance di seguirlo, Riccardo si lanciò a testa bassa in direzione del Rifugio, lungo la strada ormai quasi deserta, correndo a zig zag, dal riparo di un edificio a un altro, come se questo bastasse a evitare le bombe che da un momento all’altro potevano piovergli sulla testa. <br/>
				Alzò gli occhi per un istante e vide due aerei poco lontani, più bassi delle montagne, con i portelloni spalancati e i grappoli di bombe che roteando precipitavano giù. Respirava come un mantice e l’aria gli bruciava dentro dalla gola ai polmoni. Finché vide da lontano il Rifugio e proprio allora scoppiò sulla città l’inferno di fischi e boati, e a ognuno seguiva un frastuono di crolli e di vetri frantumati che piovevano sulla strada. In quel putiferio gli sembrò di non sentire più niente, e coprì l’ultimo tratto come un tuffo disperato. <br/>
				Un boato violento esplose vicinissimo e fece tremare la terra. Lui incespicò, solo per miracolo riuscì a tenersi in piedi e c’era quasi, vide la tozza volta che faceva da accesso al Rifugio e ci si tuffò dentro, quasi rotolò giù per i consunti gradini di pietra fino al portone massiccio che qualcuno aveva appena richiuso, ci si buttò contro prendendolo a pugni e il portone si riaprì, fu tirato dentro da dieci mani, finì accasciato per terra nel tramestio degli ultimi arrivati come lui, ancora assiepati nell’angusto ingresso. <br/>
				Per qualche istante rimase come tramortito, col cuore che gli batteva dappertutto e il sudore che gli colava a fiotti lungo la schiena. Poi tornò a essere presente a se stesso e subito si ritrovò davanti Toni e il momento in cui si era allontanato precipitosamente da lui. <br/>
				Era un verdetto senza appello. Era scappato, ci voleva almeno il coraggio di ammetterlo. Forse Silvestro aveva davvero bisogno del loro aiuto e comunque non doveva separarsi da Toni. Era stata la paura a paralizzargli il pensiero e a piegarlo al suo volere. <br/>
				Intanto cominciava a guardarsi intorno, in quel Rifugio che non conosceva. Ci era entrato solo una volta, per un inconsueto allarme pomeridiano che lo aveva sorpreso da solo da quelle parti. Era più grande di quello dell’ospedale, aveva i soffitti più alti, ma c’era lo stesso puzzo di marcio, la stessa aria umida, bagnata quasi, che adesso gli raffreddava il sudore negli abiti appiccicati. Si alzò in piedi e si fece largo fra quelli che si erano fermati nell’ingresso, e tremavano e si stringevano gli uni agli altri quando si udiva un fischio sibilare non lontano dal Rifugio e poi il boato della bomba che rintronava cupo e faceva scricchiolare le travi che puntellavano la volta. <br/>
				Aspettò un momento di calma ed entrò nell’ambiente più grande, una specie di galleria lunga quasi cento metri, con due file di panche lungo i bordi. Era piena di gente, gli uomini in piedi, i bambini sulle ginocchia delle madri, le vecchie col rosario stretto fra le dita e le labbra piegate in un’incessante giaculatoria. Cominciò a risalirla e intanto frugava con lo sguardo le persone per vedere se c’era qualcuno che conosceva. Al Rifugio dell’ospedale si ritrovava sempre fra amici e parenti e lì invece non vedeva che estranei, mentre in quel momento avrebbe scambiato volentieri due parole con qualcuno. <br/>
				Non si perdonava il proprio atto di viltà e non sopportava l’idea che potesse essere successo qualcosa a Toni, perché allora sì la sua colpa sarebbe diventata un peso schiacciante. <br/>
				Si spinse ancora avanti, solcando quella folla che come un unico corpo si contraeva e tratteneva il fiato quando risuonava il fischio di una bomba e dopo che era caduta riprendeva a respirare e ogni volta si sollevava un mormorio di sollievo e di commenti a bassa voce. Aveva anche lui paura delle bombe ma come le altre volte si sentiva abbastanza sicuro al Rifugio, anche quando le pareti tremavano e piovevano polvere e calcinacci dal soffitto. <br/>
				Arrivò ad affacciarsi sulle camerate che si aprivano ai lati nella galleria come cappelle di una chiesa, e dentro c’erano panche e  materassi gettati sull’impiantito di legno e anche lì tanta gente seduta in fila, stretti come sul tram, e tutti che lo fissavano quando metteva la testa dentro per individuare qualche conoscente. <br/>
				Finalmente, tornato nella galleria centrale, vide di spalle una testa riccioluta su una figura che gli sembrò di riconoscere e in effetti era proprio lui. <br/>
				“Ciao Carlo, sei qui con tuo fratello?” gli disse affiancandolo. <br/>
				“No, ero da mia zia quando è suonato l’allarme e sono venuto qui con lei, ma adesso l’ho lasciata con le sue amiche” rispose quello, e gli mollò una pacca sulla spalla per mostrare che era contento di vederlo. “Tu invece sei fuori zona” soggiunse, e lui si limitò ad annuire perché in realtà si stava domandando se non poteva raccontare a Carlo della faccenda di Toni. Si rispose di no, perché se ne vergognava e non era abbastanza in confidenza con lui. <br/>
				Carlo era stato un suo compagno di scuola alle Medie ma avevano continuato a vedersi, anche insieme a suo fratello maggiore, che più di una volta aveva fatto gruppo con loro ed era simpatico, non si dava delle arie come facevano sempre quelli più grandi. Si sapeva che il loro padre aveva avuto dei problemi coi fascisti, ancora prima della guerra, e che erano andati a prenderlo a casa in piena notte. Riccardo si sentiva dire da sua madre che non doveva frequentarli perché erano teste calde, ma lui non le dava retta. Gli piacevano i ragazzi con cui si trovava bene a parlare e dopo Toni loro erano i migliori. <br/>
				Fischiò vicina una bomba e vide che tanti si prendevano la testa fra le mani in attesa del boato, che esplose e si rifranse come un tuono fra le pareti. Poi si sentirono le raffiche intermittenti della contraerea, <br/>
				Carlo lo tirò per un braccio, gli fece segno di sedere con lui in un angolo sgombro, fra due panche accostate alla parete. Ma non c’era abbastanza posto per entrambi e lui sedette sui talloni, a un palmo da una bambina minuscola, che con una mano si teneva aggrappata alla gonna della madre e nell’altra stringeva una bambola di pezza. Le sorrise e lei fece dondolare la bambola, ma senza mutare la sua espressione seria. <br/>
				“Bombardano sempre più spesso. Vuol dire che si preparano all’offensiva” disse Carlo, e lui annuì, disse “L’altra notte Pippo ha tirato sulla centrale elettrica e ha colpito anche la casa dei Rensi, che abitano lì vicino”. Cominciarono a scambiarsi notizie di amici e conoscenti e dei molti che erano sfollati, dopo il pesante bombardamento di un mese prima. <br/> 
				“Lo sfollamento è un bene anche per chi resta” disse Carlo. “Prima qui si riempiva il doppio di adesso, si stava schiacciati come sardine”. Parlando ingannavano l’ansia e l’aria irrespirabile del Rifugio. Si zittivano come tutti e trattenevano il respiro quando partiva un nuovo fischio. <br/>
				Lui era contendo di aver trovato qualcuno con cui conversare. Rispondeva a tono ma era sempre concentrato su quando sarebbe finita e  avrebbe potuto uscire fuori, rivedere Toni sano e salvo e allora non gli sarebbe importato più della propria ingloriosa fuga, era disposto anche a farsi prendere in giro e ad ammettere: sì, quando ho sentito fischiare la prima bomba mi ha preso la fifa, e avrebbero riso e tutto sarebbe tornato com’era. Era quello che desiderava con tutto se stesso. <br/>
				Un fischio più acuto e prolungato riempì di paura gli occhi delle persone che avevano attorno e fece alzare di tono la preghiera che una vecchia recitava col rosario fra le dita. <br/>
				“Vogliono tagliare i rifornimenti ai tedeschi” disse Carlo alzando gli occhi al soffitto, “poi avanzeranno, e allora dovremo fare qualcosa anche noi”. <br/>
				Lui pensava ancora a Toni e per una volta gli venne da rispondere come avrebbe fatto l’amico. <br/>
				“Verranno a liberarci, ma intanto ci buttano le bombe sulla testa” disse. “Ci ammazzano e alla fine dovremo anche ringraziarli”. <br/>
				Carlo replicò con un’espressione risoluta, poi abbassando la voce disse “Se mi arriva la cartolina per arruolarmi con la Repubblica io non mi presento, vado in montagna e rimango lassù”. <br/>
				“Sono da poco arrivate le cartoline per le classi ’24 e ’25” ricordò Riccardo. “I prossimi siamo noi…”. <br/>
				Carlo piegò il capo verso di lui e abbassando ancora la voce mormorò “L’ha avuta anche mio fratello. E non si è presentato. È andato coi partigiani. E’ via già da cinque giorni”. <br/>
				Quelle parole ebbero un effetto potente su di lui. Non si aspettava che le cose fossero già a quel punto, che fosse così vicino il momento delle decisioni. <br/>
				“Coi partigiani…” ripeté. “E come ha fatto?”. <br/>
				“E’ salito al paese dove hanno la casa i miei nonni. Gli hanno detto che lì avrebbe potuto mettersi in contatto. E infatti non è più tornato. Aspettiamo notizie. Mia madre è terrorizzata ma io dico che ha fatto bene”. <br/>
				Già da qualche mese si sentiva parlare dei partigiani. Molti di quelli tornati a casa dopo l’8 settembre si erano rifugiati in montagna per non farsi prendere dai tedeschi, ma nei primi tempi si erano limitati a nascondersi e a sfuggire i rastrellamenti. Poi erano arrivate le notizie delle prime azioni: un deposito di carburante fatto saltare in aria, una spedizione punitiva contro una spia e appena una settimana prima si era saputo di un’azione nella provincia vicina, un’imboscata tesa a una camionetta tedesca, in cui era stato ferito gravemente un ufficiale della Wermarcht. <br/>Ma per Riccardo si trattava ancora di vicende lontane e fantasiose e non riusciva a immaginare di potersi davvero unire a loro, lui che non aveva mai preso in mano un’arma, e che non aveva ancora dormito una notte lontano da casa. Ne aveva parlato anche con Toni, e non aveva le idee molto chiare nemmeno lui. Però avevano concordato che indossare la divisa e andare a combattere di nuovo per il Duce non era giusto, anzi non era nemmeno da pensarci. Questo voleva dire che di lì a poco, mesi o forse meno ancora, qualcosa di ancora inconcepibile in un modo o nell’altro sarebbe accaduto. <br/>
				“Io non ho mai tenuto in mano un’arma in vita mia” mormorò per palesare solo uno dei tanti dubbi che aveva in mente, e pensò che per unirsi ai partigiani avrebbe dovuto migliorare, perché non avrebbero saputo cosa farsene di uno che al primo botto se la dava a gambe. <br/>
				“Te lo insegnano loro” disse Carlo. “Hanno quelle prese ai nemici nelle azioni. Poi ho sentito dire che gli Alleati fanno dei lanci dagli aerei e mandano giù viveri, armi, tutto quello di cui c’è bisogno”. <br/>
				Da qualche minuto erano finiti i fischi e gli scoppi e la gente cominciava a rumoreggiare e a scalpitare per uscire. Finalmente suonò la sirena del cessato allarme e la porta del Rifugio cominciò a risucchiare fuori quella piccola folla di persone ammassate. Lui e Carlo impiegarono parecchio a raggiungere l’uscita, e finalmente ritrovarono la luce del sole, che piegò loro lo sguardo dopo la penombra del Rifugio. C’era uno strano silenzio nell’aria, in fondo al quale finiva di spegnersi il fragore sordo dei velivoli che se ne tornavano da dove erano venuti. <br/>
				La gente defluiva ansiosa, accelerando subito il passo verso le proprie case per vedere in che stato erano ridotte, per ricongiungersi ai familiari da cui erano separati al momento dell’allarme, e loro fecero lo stesso. Camminavano su tappeti di vetri rotti ma a lui sembrava di non vedere grossi cambiamenti, anche se non era facile distinguere fra i danni dei precedenti bombardamenti e quelli dell’ultimo. E quasi subito gli si aprì il cuore nel vedere ancora da lontano il suo amico Toni, inconfondibile con le sue gambe magre e lunghe e il suo viso affilato che fendeva l’aria. Veniva avanti a grandi passi verso il Rifugio e appena lo vide il suo viso si rischiarò, gli corse incontro. Fu un abbraccio interminabile, accompagnato da suoni gutturali che non riuscivano a prendere la forma di parole. <br/>
				“Avevi ragione” disse poi Toni. “Silvestro era già in cantina e sono rimasto con lui e sua madre. A un certo momento i boati erano così forti che pareva la casa dovesse caderci sulla testa!” <br/>
				“Quali quartieri sono stati colpiti?” gli domandò ansiosamente lui, e Toni disse “Ho sentito che hanno preso di mira la stazione ma non sono ancora andato da quella parte. Prima volevo vedere la tua brutta faccia tutta intera”, e lui si sentì di colpo liberato da un peso. Forse non era stato grave come gli era sembrato, oppure Toni lo aveva perdonato e basta, non aveva importanza. Non glielo aveva fatto pesare e glie ne era immensamente grato. <br/>
				Ora camminavano di nuovo fianco a fianco, con Carlo che li precedeva di un passo e li guidava verso il Centro, dove dovevano passare tutti e tre per raggiungere le loro abitazioni. <br/>
				Riccardo era molto eccitato. “Il fratello di Carlo è scappato in montagna dopo che gli è arrivata la cartolina” mormorò in un orecchio a Toni senza rallentare l’andatura. “Quando ci arriva facciamo lo stesso anche noi!”. Aveva ancora in mente le fantasie sui partigiani fatte al Rifugio, e l’essersi ricongiunto con Toni lo aveva incoraggiato ancor di più. <br/>
				“Mi fa piacere vederti deciso” disse Toni “ma ci sarà tempo per pensarci” e lo guardò con un’espressione indecifrabile. Ma lui lo conosceva abbastanza per sapere che, per quanto gli piacesse fare il bastian contrario, al momento buono sarebbe stato fra i primi a fare quel che andava fatto. E tutto diventava più verosimile al pensiero di poterlo fare insieme. <br/>
				Le strade si stavano rianimando, usciva dai portoni chi era rimasto nelle case, serrande venivano risollevate e fecero un salto quando azionando il campanello una donna chiese loro strada arrivando da dietro con la bicicletta. Ma girato l’angolo della GIL cominciarono a cogliere anche segni più marcati del bombardamento: cornicioni caduti, la strada seminata di pietre e una cortina di fumo e polvere che galleggiava a mezz’aria, si infittiva man mano che si avvicinavano alla ferrovia. E la gente formicolava e rimbalzava richiami concitati, un gruppetto stava intorno a un ferito steso a terra, di fronte a una parete butterata di schegge. Più oltre videro il primo edificio sventrato e anche gli altri intorno avevano le imposte mezze divelte e penzolanti. <br/>
				Avevano cominciato a correre, quasi senza rendersene conto, imitando quelli che avevano intorno, penetrando sempre più nello scenario di distruzione. In via Cavour i palazzi abbattuti erano più di quelli rimasti in piedi, tanto mal ridotti anche questi ultimi che Riccardo non riuscì a capire se era stata distrutta o no la casa dove abitava la sua maestra delle elementari, che ogni volta lo incontrava per strada si fermava a parlare. <br/>
				Volti terrei si aggiravano intorno a quello scempio e la gente correva o si fermava sbigottita fra i cumuli di macerie, intorno ai corpi riversi sulla strada. I tre amici si tenevano stretti per evitare lo sciamare delle persone. A momenti correvano e poi si arrestavano davanti a qualcosa, si guardavano atterriti e impotenti, riprendevano a correre. Tossivano, piangevano, gli occhi e la gola bruciavano per la polvere dei calcinacci e per il fumo degli incendi. <br/>
				“Prendevano di mira la ferrovia ma hanno fatto un macello!” disse Toni, e Carlo li spinse avanti. Era il più agitato di tutti e solo allora Riccardo ricordò che la sua casa era a pochi isolati dalla stazione. <br/> 
				Era un crescendo di morte e desolazione. Di un caseggiato restava solo una quinta spalancata sul vuoto. Il palazzo a fianco si era accartocciato su se stesso come se avesse ricevuto un gigantesco pugno. Nella piazzetta ingombra di calcinacci, davanti alla fontana erano stese tre salme coperte da lenzuola. Passò un’autolettiga con la sirena spiegata, poi un sidecar con sopra due soldati tedeschi. Nei giardinetti diversi alberi erano stati sradicati. Nelle buche aperte dalle bombe la terra aveva il colore scuro dei campi appena arati. <br/>
				Le bombe avevano mutato il volto della città. Occorreva uno sforzo continuo per ricostruire la forma di edifici e angoli familiari, divenuti irriconoscibili. <br/>
				Ora si vedevano molte divise dei volontari dell’UNPA, che con pale e badili aveva cominciato a scavare intorno agli edifici crollati. I tre amici stavano passando accanto a uno di quelli quando si sentì uno scricchiolio, un fragore sordo che sembrava salire dalla terra, e in un turbine di polvere il mucchio di macerie cambiò forma mentre si alzavano alte le grida di quelli che gli stavano più vicino. <br/>
				Era il peggior bombardamento che si fosse mai visto. Dovevano esserci decine di morti, centinaia forse e loro passavano attraverso quel disastro ciascuno correndo con la mente ai propri cari, alla propria casa, costretti dallo spettacolo che avevano davanti a evocare le tragedie peggiori. Riccardo si ripeteva che i suoi dovevano per forza essersi messi in salvo al Rifugio dell’ospedale, che avevano avuto a disposizione più tempo di lui per farlo, che di lì a poco avrebbe potuto riabbracciarli. Ma bastava il pensiero del peggio per sentirsi mancare il terreno sotto i piedi, mentre si erano allontanati di colpo i pensieri sul futuro, sulla fine della guerra e sulle imprese dei partigiani a cui avrebbero potuto riunirsi. C’era bel altro prima. C’erano da scampare disgrazie irreparabili. Gli sembrava ridicola e quasi colpevole ora l’ansia provata al Rifugio, di rivedere Toni e liberarsi della vergogna per la fuga sotto le bombe. <br/>
				La strada fu bloccata per qualche istante da un’autolettiga che caricava un ferito, poi proseguirono sguazzando sulla carreggiata che grondava acqua, per qualche conduttura saltata. Erano ormai a un isolato dalla casa di Carlo che infatti si era staccato da loro e correva avanti. <br/>Accelerarono il passo ma lo raggiunsero solo quando si era già fermato, attonito, davanti a quello scenario incredibile. Si schermava gli occhi con la mano, per ripararli dalla luce abbacinante o forse per non vedere ciò che lo sguardo era incapace di accettare e comprendere. <br/>
				La casa di Carlo non esisteva più. Al suo posto un cielo che prima non c’era, e che mai avrebbe dovuto esserci, apriva spazi impudichi sugli edifici retrostanti, che sembravano rattrappiti per la vergogna di essere stati scoperti. <br/>
				C’erano dei volontari che scavavano intorno alle macerie e altre persone affannate intorno. Carlo si accostò tremante a una donna che si voltò, lo riconobbe, lo abbracciò e gli disse che i suoi erano salvi. Poi scoppiò in lacrime e aggiunse che invece erano rimasti là sotto gli anziani inquilini del primo piano, che come al solito si erano rifiutati di scappare al Rifugio. <br/>
				Carlo rimase per qualche istante immobile, paralizzato dalle emozioni che gli avevano suscitato quelle parole. Poi con uno scatto improvviso prese dalla tasca la chiave di quella che era stata la sua casa e la scagliò con rabbia contro il mucchio di rovine, contro lo scorcio di cielo nuovo e impossibile che si era aperto come un baratro nella sua vita. <br/>
                 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CHIUDI</button>
            </div>
        </div>
    </div>
</div>


    )
  }
}
