import React, { Component } from 'react'

export default class OnlineWorksUltimaSera extends Component {
    render() {
        return (
            <div class="modal" id="onlineworksultimasera" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-full" role="document">
                    <div class="modal-content">
                        <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CHIUDI</button>
            </div>
                        <div class="modal-header">
                            <h5 class="modal-title">Ultima sera dell'anno - Alessandro
            Tamburini</h5>
                            
                        </div>
                        <div class="modal-body-testionline p-4" id="result">


                            “Sicuro. Fanno tante storie e poi è una sera come un’altra,” ha detto la donna, compiaciuta; e Francesco, che da cinque giorni fa del suo meglio per essere calmo e paziente, stringe i denti ficcando gli occhi nel video perennemente acceso.<br />
                            Il televisore è di fianco alla porta-finestra; fuori c’è una nebbia così fitta, che incombe sui vetri come un sipario compatto. Da quando lui è sceso dall’auto cinque giorni fa, la nebbia non si è alzata neanche per un istante. A seconda dell’ora, può cambiare forse colore, oppure consistenza.<br />
                            Su un terrazzino dietro la grata del giardino, l’albero di natale con le palle luminose si accende a intermittenza; solo quando gli addobbi si illuminano, gli occhi percepiscono la profondità.<br />
                            Intanto, la signora Luciana come al solito ha rifiutato la sedia e non ha voluto togliersi il cappotto, dicendo “Faccio solo un salutino.” Da mezz’ora sta sulla porta, il tono del discorso è arrivato dieci volte fino ai saluti, ma poi risale immancabilmente e lei riattacca a discorrere come niente fosse. <br />Francesco non la può soffrire, ma deve far finta di ascoltare, o sorridere almeno, perché c’è bisogno di lei. Quando la nonna rimane sola, viene a vedere come sta, le fa la spesa, le porta le uova fresche dalla campagna.<br />
                            Francesco vorrebbe sperare che la nonna Stella sia un po’ diversa dalla signora Luciana e dalle altre ficcanaso del circondario, ma poi, perché negarlo? La nonna qui si trova bene, è il paese dove è nata, in fondo; lasciato sessant’anni fa, ma non conta molto. Sessant’anni, passati a seguire uno dopo l’altro quelli della famiglia; tutti artisti, per giunta. Prima il padre, poi il marito e la figlia; e lei sempre nel ruolo della donna di casa, incompresa e caparbiamente incomprensiva di quanto le accadeva attorno, sempre a protestare in cucina contro gli immancabili ospiti, perché “poi i piatti toccano a me,” e “perché non andiamo mai a mangiare a casa loro.” Quando infine è rimasta sola, tornare al paese è stata una piccola rivincita, la riaffermazione di una specie di sua inalterabilità della quale può andare davvero fiera. È rimasta viva solo lei di tutta la vecchia famiglia, e lei è la più distante fra le cose che Francesco vorrebbe ricordare; forse è proprio questo che non riesce a perdonarsi, adesso che si sono di colpo allontanati i tempi dei litigi, quando lui sbottava ogni volta di fronte al pragmatismo cocciuto della nonna. Ora, caso mai, è lui che la sgrida. Le dice “Leggi, guarda la televisione, devi tenere in funzione il cervello. Anche con la testa bisogna far ginnastica, se no si atrofizza!” Ma la nonna sta seduta nella poltrona di vimini imbottita e la sua unica occupazione è lamentarsi o disapprovare tutto e tutti; e se pure la guarda, protesta anche della televisione; in questo non è cambiata. Poi dice “Sono sempre qui sola come un cane.” Ma se viene qualcuno parla malvolentieri, non partecipa e quando l’ospite è uscito dice “Non andava mai via.” La signora Luciana è una di quelle con cui si trova meglio, perché è allegra e “viene sempre con qualcosa.” In effetti, a suo modo è una bravissima donna. Ciò che fa saltare i nervi a Francesco è il suo modo di parlare e gli intercalari, soprattutto; se dice “Come andiamo, Stella?” e la nonna risponde “Si tira avanti da poveri vecchi,” lei ripete “…Si tira avanti da poveri vecchi.” Fa così per ogni ultima frase o parola, come mettesse a fuoco o reinterpretasse i significati; il tutto scandito dai suoi “ecco,” ripetuti tre-quattro volte di seguito con accenti e intonazioni sempre diverse.<br />
                            Ma lui ha imparato a controllarsi. Sorride, annuisce, e cerca disperato con gli occhi lo schermo azzurrino della tivù.<br />
                            La nonna Stella è stanca. In realtà verso quest’ora le viene sempre un po’ di malinconia; anche lei crede che non ci si dovrebbe sentire tanto stanchi a star seduti tutto il giorno. Dice bene Francesco, che dovrebbe muoversi, e prima insisteva per farla uscire. Ma lei non si sente sicura, ha una gamba matta che certe volte la tradisce all’improvviso; non si fida. <br />Specialmente da quella volta che è caduta e per un po’ non ricordava più niente.<br /><br />

                            Stella si aggiusta sui cuscini e allunga un lembo di coperta fin sui piedi. L’unico lato bello della malattia è che può stare a casa sua e non deve più andare in nessun posto, a parte la seccatura dei raggi ogni quindici giorni; l’ospedale sarebbe anche vicino, ma è l’agitazione che le dà fastidio; è sempre stata così: si agita per un niente. Per fortuna le ultime lastre le ha fatte da poco e adesso per un po’ non ha da pensarci; e per la spesa c’è Luciana: ha le gambe buone lei, può andare dove vuole!<br />
                            Francesco la sgrida perché non si sforza di leggere e quando viene qualcuno sembra le dia fastidio. Ma è che raccontano sempre le stesse storie, e poi, quando può stare coi suoi nipoti è già contenta e degli estranei le importa poco. È buono Francesco, ha pazienza! Quando lo chiama, di notte, per andare in bagno, viene subito ed è pieno di premure. Le dispiace di sveglialo, ma come si deve fare?<br />
                            Adesso Luciana potrebbe decidersi ad andare: non vede che ormai è ora di cena? Non si va a quest’ora a casa della gente. Meno male che Francesco è gentile con lei.<br />
                            Però si vede, che fa un po’ fatica. Quanto è stata in pena per quel ragazzo, quando sembrava che avesse solo idee balzane per la testa. I genitori erano morti da poco, così che era tutta sua, la responsabilità. Si sa quanti ce ne sono che vanno a finir male! Anche lui pensava solo a fare l’artista; come il nonno, come la povera Giulia; ed è una vita dura, Stella se lo ricorda bene: pochi soldi e troppe pretese; e lo sa lei che fatica arrivare alla fine del mese. Poi un bel momento ci si era messa anche la politica, le dimostrazioni; con lei che andava avanti e indietro dalla finestra; e che pensieri, finché non lo vedeva tornare. Per fortuna adesso ha messo la testa a posto, ha un lavoro sicuro e sembra che sia contento. È stato fortunato, si è trovato quella ragazza che è brava; in casa non deve valer molto, ma gli vuol bene e lui ne sarà innamorato, perché quando le telefona sta fuori non si sa quanto. Come si chiama? Adesso non se lo ricorda… Pensa che è strano far fatica a tenere a mente le cose del giorno prima e quelle di una volta ricordarle tanto bene.<br />
                            La borsa dell’acqua calda si è raffreddata, ma Stella non dice niente perché Luciana è sempre sulla porta. Poi, bisognerà mettere in tavola qualcosa per cena; non mangia mica tanto, Francesco; è magro come suo padre. Chissà cosa mangia quand’è solo con la sua ragazza. Magari sono capaci di andare avanti a pizze e panini; e non fa bene, ma lei spera che in due abbiano almeno un po’ più di giudizio. Comunque, questi giorni che è qui ha cercato di farlo mangiare. <br />
                            Adesso chiede che ore sono, e Francesco dice “Le sei e mezza.” <br />Pensa che sono lunghe queste giornate, e che alle quattro è già buio e si fatica a far venir sera.<br />
                            Poi si stringe nella coperta, tira fuori una mano con la borsa dell’acqua calda, e dice rivolta a Francesco “Per favore…”<br /><br />

                            Finalmente, con uno strascico di auguri e scongiuri, la signora Luciana s n’è andata. Per strada si sente un botto di prova; mancano ancora tante ore alla mezzanotte, Francesco preferisce non pensarci. Non ha ancora trovato un approccio psicologico che gli sembri adatto alla circostanza; di tanto in tanto guarda l’orologio con una sottile apprensione.<br />
                            A quest’ora Milly forse si starà vestendo. Anzi, di certo starà ancora facendosi lo shampo, con gli altri che l’aspettano di sotto già da un po’. È diventato quasi una favola, lo shampo di Milly, e lei stessa, tanto è abituata alle proteste degli altri fuori dalla porta del bagno, dice che quando è sola e tranquilla, dietro il ronzio del phon crede sempre di sentire i rimproveri. Almeno stasera non sarà lui, a dirle di sbrigarsi.<br />
                            Intanto la nonna già scalpita per la cena. Lui che è abituato a cenare dopo le nove, da cinque giorni si mette a tavola prestissimo e mangia poco o niente. Poi sparecchia, lava i piatti, mette a letto la nonna e accende sotto l’acqua per gli spaghetti. Ma stasera no. È l’ultimo dell’anno; gli pare che un po’ di forma sia proprio indispensabile.<br />
                            La signora Luciana ha portato i tortellini. Mentre li mangia la nonna dice “Buoni,” e lo guarda sottecchi. Lui dice “Buoni, ma con i tuoi non c’è neanche paragone.” E lei sorride rassicurata. “Mi dispiace che passi un brutto capodanno,” dice.<br />
                            Lui fa segno di no con la mano, manda giù un tortellino e gira la testa verso la tivù. “…Infiniti auguri per un felice anno nuovo!” ripete per l’ennesima volta l’annunciatrice dello schermo, e la nonna dice “Grazie cara.” Dialoga spesso con la tivù, che poi è la sua principale compagnia, ma questi giorni la segue meno perché c’è lui. Da quant’era che Francesco non stava a casa con lei l’ultimo dell’anno?<br />
                            Lei si è ammalata all’improvviso. L’hanno ricoverata il giorno di Santo Stefano che quasi non respirava. E subito, raggi, esami, medicine, e la flebo sospesa accanto al lettino in ospedale. Si è un po’ ripresa, adesso, e per capodanno hanno rispedito quasi tutti a casa. Così ci voleva qualcuno ad assisterla. Doveva restare anche Marco, il nipote prediletto, ma si è fermato solo un pomeriggio e non si è mai tolto le cuffie dalle orecchie, molto preso da una musicaccia rock ronzante per tutta la casa. Francesco l’ha rispedito subito in città perché ha avuto pietà dei suoi sedici anni appena compiuti. <br />
                            La cena è finita e l’orologio segna le sette e un quarto. Lo sguardo deve tradirlo in qualche modo, perché la nonna gli chiede “Cosa fai adesso, vai a telefonare?”<br />
                            “Si, arrivo fino al bar e faccio gli auguri a Milly. Ma tu prometti che m’aspetti seduta in poltrona e non ti metti a lavare i piatti e non accendi il gas sotto la pentola vuota come hai fatto ieri!”<br />
                            “…Non spender tanti soldi con quel telefono,” replica la nonna, mentre lui si veste. <br />
                            Mente di nuovo per rassicurarla. Dice “Faccio presto, prendo pochi gettoni.”<br />
                            Quando si è avvolto la sciarpa intorno al collo, scende le due rampe di scale. Si affaccia dal portone e rimane fermo per un istante davanti alla coltre di nebbia che stagna sulla strada.<br /><br />

                            Questo paese è uguale a cento altri, quando non c’è la nebbia. Molto di rado, d’inverno. Milano non è lontana, ma nella Padana è così: Francesco si sente perduto in uno spazio indistinto, tra campi coltivati fino alla strada, file rade di alberelli, e la mole arcigna dello zuccherificio che riempie col suo odore dolciastro l’automobile e l’incerto orizzonte fino all’argine del Po. La strada è tutta dritta, rettilinei di chilometri e chilometri, fino alla serie di curve a gomito che aggirano le proprietà e i muri di cinta delle ville. Poi, ancora rettilineo a perdita d’occhio. I paesi sono tutti simili, due file di case lungo la provinciale fino alla chiesa, la torre con l’orologio, la piazza con i portici dove uomini e donne in bicicletta vanno talmente piano che certi sembrano sempre sul punto di cadere da un lato.<br />
                            Se chiedi un’informazione, ti guardano smarriti e le indicazioni sono complicatissime e scoraggianti. Poi, se t’incammini per conto tuo, magari giri l’angolo e sei arrivato.<br />
                            Francesco esce poco di casa, quando è in paese dalla nonna. Compra in fretta quel che occorre e va a telefonare. Chiede la linea a un barista che lo guarda inclinando la testa, come se fare un’interurbana sia un’impresa dalle motivazioni imperscrutabili e dall’esito misterioso.<br />
                            Lui fa il numero, e appena senta la voce all’altro capo del filo tira un sospiro di sollievo. Ma stasera non deve telefonare a nessuno; Milly di certo non è più in casa; gli amici hanno organizzato la festa in una baita in montagna dove non c’è telefono, e lui pensa che così è una bella libertà per tutti; anche per lui.<br />
                            Lui non è felice di passare il capodanno a casa con la nonna, eppure non si nasconde un certo sollievo. L’ultimo dell’anno è una sera delicata, piena di ansie, dalla quale a dispetto di ogni buon senso ci si aspetta ogni volta qualcosa di speciale.<br />
                            Ogni capodanno è un giocattolo nuovo di Milly e bisogna sceglierlo bene e guadare che non si rompa; con lei a capodanno si può essere felici o infelici, commossi o estranei o feriti per un nonnulla, ed è l’infelicità di Milly che gli fa paura, perché ne sentirebbe subito su di sé la responsabilità. De Amicis, si. Ma anche dov’è adesso le cose sanno parecchio di Libro Cuore; lui pensa “Sangue romagnolo,”: s’intitolava così il racconto in cui il ragazzo mezzo delinquente si fa ammazzare dal ladro per difendere la nonna…<br />
                            Cammina sotto i portici e il rumore dei passi rimbomba forte sotto la cappa di nebbia che lo imprigiona tra le colonne. È tutto chiuso e buio per le strade; sono le otto, la gente mangia o sta davanti allo specchio, si prepara ad uscire. Questo è il primo capodanno che lui e Milly passano lontani da quando stanno assieme, e sono quanti anni? Sette giusti. È pensando a lei, che Francesco ha declinato l’invito della bella infermiera di nome Lucia; e neanche adesso, mentre si aggira solo e sconsolato sotto i portici, se ne pente.<br />
                            Lucia è infermiera al reparto geriatrico, e all’ospedale è stata sempre molto gentile e premurosa. Lei veniva a chiacchierare certe volte, quando lui usciva in corridoio a fumare una sigaretta, e così hanno familiarizzato.<br />
                            Lucia ha capelli folti e crespi e sopracciglia marcate che rendono un po’ accorato ogni suo sguardo appena intenso; ha un tono di voce penetrante, sa quello che vuole e lo persegue senza esitazioni.<br />
                            Quando lo ha invitato a un veglione di fine d’anno, gli ha detto che avrebbe pensato lei a trovare una brava donna che si occupasse della nonna, e già che la trovava, - ha specificato con un sorriso aperto,- avrebbe fatto in modo che restasse fino la mattino.<br />
                            Lui in un primo momento si è detto “Me lo merito e non farei del male  a nessuno.” Ma poi si è tirato indietro.<br /><br />

                            Quando lui ha chiuso la porta, Stella si è preparata a combattere la sottile paura che la prende sempre un po' quando rimane sola. Ha paura di sentirsi poco bene, ha paura dei rumori, e allora guarda continuamente verso l'ingresso; ha paura di accorgersi ogni volta di essere più debole, incapace anche solo di alzarsi a prendere un bicchier d'acqua se le viene sete. Per fortuna non è tardi, la signora Rosa al piano di sopra sta mettendo in tavola per il marito e la figlia; si sente il tintinnio dei piatti. E Francesco starà via poco, è tutto chiuso a quest'ora; del resto anche lui ogni tanto  dovrà pur muoversi, povero figliolo, sempre chiuso in casa con una vecchia malata! È contenta, perché pensa che anche stanotte Francesco dormirà sul letto dell'ingresso e questo la fa addormentare tranquilla. Che brutto diventar vecchi, aver bisogno degli altri, aver paura di tutto. È già più di un anno che non esce di casa e da quando è ammalata anche quelle quattro stanzette sono diventate uno spazio troppo grande e impegnativo per lei; precede col pensiero ogni passo preparandosi agli appoggi che conosce, il tavolo del salotto, lo schienale della vecchia Frau, la maniglia della porta, il comodino.
Pensare, che quando c'era il babbo abitavano in un palazzo tutto loro, con tante finestre che per chiuderle tutte, alla sera ci voleva mezz'ora. Era compito suo, e certe volte c'era da spaventarsi, al buio, lungo quei corridoi che non finivano mai, con tante porte aperte sulle stanze scure. Adesso tutti le ripetono che dovrebbe muoversi più che può, almeno in casa; per il compleanno le hanno regalato un bastone proprio bello, ma a lei non piace e l'ha lasciato nel portaombrelli; è troppo da vecchia girare col bastone! Però adesso dovrebbe proprio andare in bagno. Tutta colpa di quelle medicine che le fanno prendere. Anche in ospedale era un problema, perché poi le infermiere si scocciano a chiamarle di notte, si capisce; ma come si deve fare? Bisogna che provi ad alzarsi da sola, non può mica farsela addosso. E forse, intanto Francesco tornerà. Punta forte i polsi sui braccioli della poltrona e valuta la distanza che la separa dal tavolo.<br />
                            Sarà il primo traguardo da raggiungere. Pian piano si alza in piedi, il tavolo è vicino, ma adesso viene il passaggio più difficile. Fino alla porta del bagno non ci sono più appigli. E poi c'è quella mattonella che si muove sotto i piedi e di cui lei diffida moltissimo. Avanza in un vuoto di due metri che le pare un ponte sospeso e tremante, socchiude gli occhi e mette avanti una mano. Quando finalmente tocca l'angolo dell'ingresso pensa che da lì in poi è tutto facile, ce l'ha fatta. Accende la luce del bagno e respira; quando passa davanti allo specchio e si guarda con noncuranza, decide che per qualche istante può giocare a sentirsi una vecchietta arzilla; il bagno è pieno di appoggi sicuri.<br />
                            Mentre sta uscendo sul corridoio sente dei rumori che vengono dalla porta.<br />
                            "Sei tu Francesco?" dice forte, per farsi sentire dal nipote; ma le sembra che i rumori continuino e che nessuno risponda. Arretra di un passo e si appoggia al lavandino. È sicura che la porta si sia aperta e dunque non può essere che Francesco, ma perché non dice niente?<br />
                            Dei passi che non conosce risuonano nell'ingressino, e Stella è ancora immobile sulla porta quando dal corridoio compare la sagoma infagottata di sua cugina Elena.<br /><br />

                            *
    
<br /><br />Mentre apre la porta d'ingresso, si accorge che la poltrona di vimini è vuota. Ha un attimo di spavento quando vede che anche in bagno la nonna non c'è. Dice "Nonna, dove sei?" e infila di corsa il corridoio.<br />
                            "Siamo qui, siamo qui," risponde da in fondo la voce della zia Elena.
Trova la nonna già sotto le coperte, con la borsa dell'acqua calda stretta al petto. La zia Elena è seduta in poltrona e gli sorride come sempre, appena lo vede; si occupa lei della nonna quando deve tornare in ospedale; anche con lei occorre quindi essere tolleranti e pazienti. Quando è arrivato in paese, Francesco le aveva detto "Ora sono qua io, approfittane per pensare alle tue cose, che ne avrai da fare!" Ma lei non sa rinunciare alle sue visite serali, nemmeno stasera che è l'ultimo dell'anno. È una superattiva, non sta mai ferma, e naturalmente parla in continuazione. L'ultima volta che sono stati a mangiare a casa sua, - sono passati molti anni da allora, - mentre gli ospiti terminavano il pranzo lei era già in piedi, e, sempre parlando, spolverava con ogni cura le porcellane.<br />
                            Suo marito, poveretto, ha già avuto due infarti e lei ne parla come di un orfano preso in casa da bambino. Hanno una villetta a due piani, con un bel giardino. Però stanno sempre nel garage, che hanno riadattato con cucina, divano e televisore. Salgono al piano di sopra solo per dormire e prima di salire si tolgono le scarpe. La zia Elena ci sale più spesso, per pulire. Persino la nonna una volta le ha chiesto “Ma cosa c’è da pulire se non ci state mai?” E lei ha risposto decisa “Beh, un po’ di polvere c’è sempre.”<br />
                            Adesso anche Francesco si è seduto di fianco al letto, ma vorrebbe non ascoltarla: incidenti, disgrazie, malattie, sono i suoi argomenti preferiti e ad ogni visita un solo episodio le basta, perché il suo personale legame con la vittima richiede sempre ricostruzioni complicatissime. Stasera c’è un incidente d’auto fresco fresco. “Sempre a quell’incrocio, e con una nebbia così! Per fortuna non ha sofferto, l’hanno trovato che era bell’e morto…”
                            La nonna ha un po’ di tosse, le viene la sera, appena si mette a letto. Fra un colpo di tosse e uno starnuto chiede “Ma chi è morto?” L’altra non ha neanche pigliato fiato che riprende a raffica “Non sai chi era? Era il fratello del dottore che abita fuori Porta Pieve, quello che ha curato il povero nonno Ernesto.” Lui pensa: chissà quale sottile piacere trova nel contemplare le disgrazie altrui, è come una passione; e non si può neppure criticarla perché sceglie argomenti simili con una malata: lei non saprebbe parlare d’altro.
Si volta ispirata verso Francesco e dice “E tu Nano, non hai mica avuto niente, eh?”<br />
                            Lui non capisce, dice “Niente cosa?”<br />
                            “Voglio dire,” insiste lei, “che sei mingherlino ma stai bene, non hai ancora avuto niente!”<br />
                            Lui scuote la testa e risponde “No, ringraziando il cielo,” ma avrebbe sulle labbra un’imprecazione fulminante, quando, senza farsi vedere, tocca la maniglia della finestra. “Il mio Nano!” conclude la zia Elena. “Come assomiglia al povero nonno Ernesto!”<br />
                            Sul piano di marmo del comò, tra foto di parenti morti, santini e papagiovanni, le lancette della sveglia stanno per sovrapporsi. “Sono quasi le dieci,” annuncia Francesco speranzoso, e la fortuna lo assiste. La zia Elena si alza e fa per andare. “Addio cara, ti lascio qui col tuo bel giovanotto,” dice. “Stai meglio di me…”<br />
                            “Siamo qui a casa noi due soli,” dice la nonna.<br />
                            “Beh?” fa lei, “sono tanti anni che stiamo a casa, noi, per capodanno. Dove vuoi che si vada? E poi bevono e succedono tanti di quegl’incidenti che non si ha un’idea.”<br />
                            Quando Francesco l’accompagna alla porta, la saluta più cordialmente che può. Appena richiude si appoggia al muro un istante e pensa: “Che io sia diventato tanto buono per davvero?”<br />

                            “Non andava più via,” brontola la nonna. Poi dice “Cosa c’è Francesco? Ti spiace di dover stare a casa, eh?”<br />
                            “No no,” risponde lui. “È la zia Elena che mi dà un po’ sui nervi.”
“Si, lo so,” dice la nonna. “Ma è una buona donna, ci vuol pazienza…”<br />
                            I discorsi della zia Elena gli hanno fatto perdere improvvisamente gran parte della tranquillità di spirito con cui avrebbe voluto affrontare l’arrivo della mezzanotte. Adesso si sente perfino afflitto, in preda a uno sconforto sottile che crede di non riuscire a nascondere.<br />
                            “Siediti qui,” gli dice la nonna. “Raccontami qualcosa.” E lui si mette ai piedi del letto e pensa che quella visita ha già agitato anche lei, che adesso ha ripreso a tossire e le lacrimano gli occhi e s’è fatta rossa in viso. Lui tira fuori le caramelle, ma la tosse non si calma. Allora ha un’idea: “E se ti facessi un po’ d’acqua calda con lo zucchero?”<br />
                            Il viso della nonna s’illumina. Dice “Ma si, ma si. Forse mi fa bene.”
Quando ritorna con la tazza fumante in mano dice “Me l’hai insegnato tu come rimedio per la tosse, ti ricordi?” E mescola col cucchiaino meticolosamente.<br />
                            “Scotta?” fa lei.<br />
                            “No, è giusta, bevila subito. Se non è calda non fa effetto.”<br />
                            La nonna si alza a sedere sul letto e beve a piccoli sorsi, mentre lui le sorregge la schiena.<br />
                            “Piangevi, alla notte,” dice quando si sdraia di nuovo. “Se faceva tanto da venirti la tosse ti durava giorni interi! Tossivi che ti sentivo io dalla mia stanza, ma tuo padre e la mia povera Giulia non ti sentivano, o non volevano sentire… Perché si capisce che era più comodo che m’alzassi io; bastava un po’ d’acqua e zucchero e stavi subito meglio.”<br />
                            “Vedi nonna,” dice Francesco sorridente, “adesso io la porto a te, così siamo pari.”<br />
                            “E il caffè con dentro l’uovo sbattuto, lo prendi ancora la mattina?”
“Si, ma di rado, perché non ho mai tempo, e ci metto meno zucchero.”<br />
                            “Pensare che da piccolo per il pane burro e zucchero ci andavi matto,” dice la nonna. Poi improvvisamente cambia tono, come a dire sto al gioco, faccio finta di niente, ma adesso parliamo sul serio. “Cosa pensi, Francesco, che potrò stare un po’ meglio?”<br />
                            “Ma certo,” risponde lui. “L’età c’è, si capisce, ma tornerai in forma e magari faremo ancora qualche giretto insieme.”<br />
                            “Qualche giretto dove?”<br />
                            “Per esempio ti potrei accompagnare alla commemorazione del nonno, in primavera; ti ricordi come sei stata contenta l’altr’anno a teatro, quando ti hanno chiamata sul palco e ti hanno chiamata sul palco e ti hanno fatto anche l’applauso?”<br />
                            Le spuntano due lacrime per la tosse, e dice “No, in giro non vado più, tocca a te adesso tenere alto il nome della famiglia.” Così lui si sente triste da morire, e stanco, anche. Ha voglia di andare a letto e fregarsene della mezzanotte.<br />
                            Le dice “Quasi quasi vado a letto anch’io. Ti va di provare a dormire?”<br />
                            Lei dice “D’accordo.” Poi aggiunge “Spero di non doverti svegliare, stanotte.”<br /><br />

                            È di nuovo in cucina, e per prima cosa decide di cambiare le luci. Accende l’abatjour vicino al divano e la scherma col quotidiano aperto sullo schienale della sedia. Così gran parte della stanza resta in ombra; ed è meglio, perché la cucina è l’ambiente in cui la nonna ha seminato più immagini religiose e foto di parenti defunti e rametti di ulivo appesi ai ganci dei quadri e scatole di ammennicoli piene di bottoni, biro senza inchiostro, vecchie cartoline…<br />
                            Sono solo le dieci e mezzo, e la decisione di andarsene subito a letto con un libro gli si è completamente dileguata. Pensa che non è divertente mettersi a letto cercare di addormentarsi sapendo che a una certa ora della notte - magari alle tre o alle quattro - la voce della nonna gli si insinuerà nel sonno perché ha bisogno che lui la aiuti. Poi, quello sarebbe poco male; è che così lui non riprende più sonno: dopo, rimane con l’orecchio teso a ogni piccolo suono, e di notte gli sembra che la casa ne sia piena.<br />
                            A quest’ora Milly starà ballando di certo. Ballare le piace da matti, lo ha persino convinto a prendere qualche lezione per farle da degno cavaliere. Stasera si sarà messa senz’altro il vestito nero filettato di perle e le scarpe col tacco alto.<br />
                            Sorride, mentre la immagina che scende dall’auto e avanza con i doposci nella neve alta, tenendo le scarpette lucide in mano.<br />
                            Gli sembra che sia molto bello il capodanno in montagna, per il fuoco nel camino e il freddo intenso fuori; con la notte che pare più fonda, come dev’essere l’ultima notte dell’anno, senza luna né stelle, chiusa nella neve, da attraversare dopo mezzanotte con le torce comprate al negozio dei vigili del fuoco.<br />
                            Accende la televisione e cambia tre volte canale ma il programma è sempre lo stesso in ogni stazione: abiti da sera, sorrisi tremendi e aggiornamenti continui sui minuti che mancano; lascia il volume a zero, per il conto alla rovescia finale. Pensa che è proprio così, il capodanno non perdona! All’ultimo momento gli pare che ci vorrebbe qualcosa di speciale anche per lui, chiuso nella cucina della nonna, e si consola pensando alla bottiglia di whisky che ha comprato al mattino, per un brindisi solitario potrà anche andare bene, ma sono solo le undici e la crisi di tosse della nonna gli suona quasi come una salvezza. Crede che adesso c’è ancora qualcosa a cui pensare.<br /><br />

                            Gli dice “Scusami,” mentre cerca di mettere un piede giù dal letto. “Purtroppo mi devo alzare. È tutta colpa delle medicine.” Poi aggiunge “Dormivi?”<br />
                            Lui dice “Ero sveglio, non preoccuparti.” La aiuta ad alzarsi, e lei tossisce forte, diventa rossa e fa la faccia avvilita. “Non sto mica bene,” fa sconsolata. <br />
                            Le dà il braccio prima che lei muova un solo passo.
Lei dice “Con l’acqua e zucchero mi era andata via… Poi ho fatto un sogno strano…”<br />
                            Lui pensa che i medicinali non sono bastati per addormentarla e l’hanno lasciata stranita.<br />
                            Lei dice “Ho sognato la mamma, era sulla porta coi capelli raccolti a crocchio, che bei capelli aveva, stava dritta sulla porta e mi guardava. All’inizio pensavo fossi tu, poi l’ho riconosciuta. Ho detto: ‘Mamma, siete voi? Avete bisogno di qualcosa?’ Credi che sia venuta a prendermi, eh Francesco?”<br />
                            Lui le stringe forte il braccio. Dice “Ma va’ nonna, per un po’ di tosse… Tu ci seppellirai tutti, mio padre lo diceva sempre!”<br />
                            Lei dice “Per l’amor di Dio, il mio Francesco, il mio Marco!” Quando torna sotto le coperte lui mette altra acqua a scaldare e si siede in fondo al letto. Ha più voglia di lei, di chiacchierare. “Che brutto capodanno ti faccio passare,” dice la nonna. “E Milly?... Dirà: quella brutta vecchia!...”<br />
                            Lui ride. Dice “Ogni tanto star lontani non fa male. Lo scorso anno ad esempio abbiamo litigato.”<br />
                            “Ci vuol pazienza ci vuole, l’avrai fatta arrabbiare!”<br />
                            “Ma no, è stata una sciocchezza, un malinteso…”<br />
                            Lei socchiude gli occhi e sembra sul punto di riaddormentarsi. Invece ha un nuovo attacco di tosse e si alza a sedere sul letto; beve ancora un sorso d’acqua e zucchero, prima di rimettersi giù. Poi dice “Raccontami, non mi dici mai niente di quel che fai.” “Eravamo in montagna, a cena  con due nostri amici in un bel ristorante rustico; sai, tutto in legno, con le cameriere in vestito tirolese, l’orchestrina in knicker-bockers… Fino a mezzanotte tutto bene, abbiamo mangiato e bevuto; a dire la verità abbiamo bevuto troppo: vino, champagne, whisky, amaro… Ecco, dev’essere stato l’amaro il colpo di grazia… Comunque, quando siamo usciti facevamo fatica a stare in piedi, e non certo per via del ghiaccio; a me girava la testa e mentre gli altri facevano manovra con l’auto mi sono avviato a piedi. La strada era in leggera discesa e pensavo che m’avrebbero raggiunto subito. Così mi sono sentito subito meglio, stavo benissimo, tanto che mi sono dimenticato di tutto, mi lasciavo andare verso le luci del paese e dalle case in fondo usciva molta gente in festa, c’era tanta neve, e a tratti un grande silenzio e un freddo da morire, ma asciutto che non si sentiva niente. E io, che ero brillo forte, gridavo a tutti ‘Buon anno, buon anno!’ ed ero contentissimo. Però, camminando devo aver superato un incrocio, credo; fatto sta che mi sono perso, o comunque gli altri non sono più riusciti a trovarmi. Quando finalmente è spuntata la macchina dei miei amici ero già intirizzito e stanco, e a vedere la faccia di Milly l’allegria mi è passata del tutto; mi guardava come se fossi un traditore. Ha detto che ero andata via da lei proprio nel momento più bello, all’inizio dell’anno nuovo, e che non me l’avrebbe mai perdonato. Poi in macchina è stata male, ha anche rimesso. E a quel punto, naturalmente, era tutta colpa mia.”<br /><br />

                            Con la bocca semichiusa e la guancia appoggiata sopra il palmo della mano, la nonna si è riaddormentata. L’orologio segna le undici e venti; lui torna in punta di piedi in cucina un po’ sollevato: pensa che tra poco più di mezz’ora sarà tutto finito e gli torna in mente una frase che diceva sempre la nonna quando lui non voleva mangiare la fettina: “Tagliala sottile, fa’ dei bocconi piccoli e manda giù senza pane.” Gli sembra che così sia anche per il tempo, per la vita, quando non vuole andar giù.<br />
                            Dallo schermo il presentatore muove la bocca come in un film muto e assomiglia perfettamente a un pinguino vestito; la valletta ha due labbra enormi, e deve essere molto su di giri. Pare le si muovano persino le orecchie, quando ride.<br />
                            Fuori dalla finestra la nebbia è sempre fitta. Solo dai piani alti dei palazzi viene qualche bava di luce, e a tendere l’orecchio si possono indovinare le parole allegre dette ad alta voce durante le cene casalinghe, i brindisi per l’anno vecchio e le risate di chi  ha bevuto già troppo. Certo, di tutto questo Francesco non ha invidia alcuna. Anzi, gli ultimi minuti prima della mezzanotte fatidica lo hanno sempre messo in un certo imbarazzo, in una specie di goffaggine che si sente addosso a concentrarsi così sul tempo che passa o che verrà, o che è perduto. È bello solo dopo, quando si dice “Questo è il primo bacio dell’anno, questa la prima sigaretta,” o quando è la prima volta che si scrive la data col nuovo numero finale e ancora non ci hai preso nessuna confidenza.<br /><br />

                            Quando mancano ormai solo pochi minuti, decide che è il momento di riempire il bicchiere di whisky. Poi gli sembra che ci vorrebbe ancora qualcos’altro, e ha una piccola illuminazione mentre gli viene in mente l’amico William.<br />
                            L’ha incontrato il giorno della partenza e gli ha detto delle sue poco rosee prospettive per il capodanno. William si è guardato attorno circospetto, poi ha trafficato nelle tasche del paltò e gli ha messo in mano un cartoncino dicendo “Tieni questo, per i momenti difficili.”
“Ma cos’è?” aveva chiesto lui ridendo.<br />
                            “Cosa vuoi che sia?” ha detto l’altro sornione. “Erba, erba di campo!”
Sorride mentre pensa al vecchio William che lavora quando gli capita, dorme da un amico, e fa imperterrito la stessa vita che facevano insieme dieci anni prima, quando erano entrambi all’università.<br />
                            Lui non fuma erba da chissà quanto e non è che ne sia mai stato tanto entusiasta, perché si è convinto che gli dava sonno e mal di testa dopo i bei sogni fitti e colorati. Ma a mezzanotte meno cinque anche una piccola scusa così va bene. Adesso non è neanche sicuro di averla messa in valigia…<br />
                            Quando la trova, vuota una sigaretta e sbriciola col tabacco il fiorellino opaco e rinsecchito.<br /><br />

                            Nella tivù a zero volume le enormi lancette di un orologio stanno per sovrapporsi sulle dodici. Ecco, è l’ora, è mezzanotte. Francesco alza il bicchiere colmo di whisky e brinda ad alta voce. “Buona fortuna, buone occasioni!” dice, mentre accende la sigaretta che ha ricomposto col fiore sbriciolato. Per le strade del paese i botti partono a raffica e fuochi d’artificio multicolori perforano la nebbia sibilando e fischiando prima di scoppiare in mille punti luminosi; si aprono le finestre, qualcuno grida dai terrazzi e fra tanti rumori venuti a infrangere il silenzio di prima sente che c’è la tosse della nonna. L’hanno svegliata i botti di mezzanotte, e mentre corre in corridoio, tossisce anche lui per il fumo secco che gli scende in gola e non sa che farne di quel mozzicone mezzo storto… Entra nella stanza tenendolo dietro la schiena. Accende l’abatjour sul comodino e la nonna dice “Che or’è, è già mattina?”<br />
                            “No, è appena mezzanotte. Buon anno, auguri!”<br />
                            Lei dice “Auguri, auguri a te che sei giovane!” Poi aggiunge “Cosa fai, fumi?”<br />
                            “Si, nonna. Scusami… la spengo subito.”<br />
                            Ma lei ha uno sguardo furbo e forse pensa al capodanno, e che l’anno prossimo chissà dove sarà, dice “Va là, fammi fare una tirata.”<br />
                            Francesco resta di stucco. Dice “Ma nonna, saranno vent’anni che non fumi, e poi hai la tosse, sei malata…”<br />
                            “Appunto,” fa lei decisa. “Mi piaceva a me la sigaretta, m’han detto di smettere e mi sono ammalata lo stesso, fammi dare una tirata, su.”<br />
                            Cerca disperatamente una frase che possa convincerla a rinunciare e invece le porge la sigaretta come se fosse un tizzone ardente. Dice “Un tiro solo, però,” con voce implorante.<br />
                            La nonna prende il mozzicone fra le dita e se lo porta alle labbra con una naturalezza antica, dà una tirata e subito tossisce, però dice “Buona! Che sigarette fumi adesso?” Lui fa per riprendergliela ma lei ritira la mano, ne aspira ancora, tossisce, ma non la lascia andare. Alla fine riappoggia la testa sul cuscino e sembra soddisfatta.<br />
                            “Mi ricordo che ti piaceva fumare,” dice lui rinfrancato. “E alla mamma dava fastidio e ti chiudevi sempre in cucina… E adesso,” aggiunge, “devi andare in bagno?”<br />
                            “No no,” fa lei. “Adesso dormo. Vai anche tu a dormire, grazie Francesco, buon anno. Ci vediamo domattina.”<br /><br />

                            La casa e le strade sono tornate silenziose. La nebbia, oltre i vetri, ha riassorbito i fuochi della festa e solo di tanto in tanto un rombo d’auto corre veloce sotto le finestre e va a spegnersi nel rettilineo del viale. <br />
                            Francesco chiude le persiane e scopre il cuscino, fa la piega a quelle lenzuola di canapa che non ha mai visto da nessun’altra parte, e gli pare che anche quel fiore secco qualcosa ha pur fatto, perché si sente di colpo più quieto. Forse è solo più stanco, ma in ogni caso ha voglia di addormentarsi. <br />Si, gli effetti sono sempre quelli di una volta, un leggero capogiro che passa appoggiando la testa sul cuscino, e una sequenza di immagini una dietro l’altra, come un film accelerato che porta dritto in un sogno ad occhi aperti e infine al sonno. La nonna non tossisce più e forse farà tutta una dormita fino a domattina. Pensa che sarebbe un bel regalo, per la prima notte dell’anno.<br />
                            Mentre socchiude gli occhi, trova i volti che gli animano i pensieri di oggi e quelli di ieri: ci sono Milly e Lucia, William che cammina nella nebbia e la nonna seduta sulla poltrona di vimini. Gli sembra, attraverso il corridoio buio, di sentire il respiro sereno di lei che si è appena addormentata.<br /><br />

                            Dorme su un fianco e stringe col braccio la borsa dell’acqua calda. È entrata in un sogno fitto e colorato.<br />
                            Si sporge dalla finestra e sente che fa caldo e che i gerani avvampano di odori, il cortile è pieno di sole e in lontananza, confuse dal riverbero, vede le sagome dei bambini che corrono dietro al pallone. Lo chiama due volte ad alta voce. Quando arriva, lui guarda trafelato verso il davanzale. Dice “Tira!” e lei gli lancia il sacchetto col pane imburrato e zuccherato.<br />
                            La voce di suo padre la chiama: è tardi, è già buio, e bisogna chiudere le finestre. Lei chiude per prima quella coi gerani, accosta le persiane della cucina ed esce in punta di piedi per non svegliare Francesco e Milly che gli dorme accanto abbracciata. Attraversa la sua casa, quella di adesso, ma le tre stanze si moltiplicano… Oltre la sua, col letto ancora aperto, c’è un’altra porta, un’altra stanza e poi un’altra, e qui ci sono i mobili della sua casa di una volta, la credenza di noce, le statuine dei lanceri del ‘600 vendute alla fine della guerra, per comprare da mangiare.<br />
                            Riconosce lo studio del babbo con la grande scrivania piena di cassetti e le colonnine sui lati, chiude le altre finestre e percorre i corridoi a passo svelto: non ha paura, perché Francesco sta dormendo in cucina, davanti alla porta d’ingresso. Il corridoio si allunga e si stringe, com’era in casa di Giulia, con gli scarponi militari messi ad asciugare davanti alla stufa di ghisa; suo genero è ufficiale del Genio, e come ogni sabato c’è la divisa da lavare e stirare.<br />
                            Nelle tre stanze della sua casa, che pure conosce palmo a palmo, ci sono spazi ulteriori che non aveva mai visto, angoli nascosti e passaggi segreti.<br />
                            Le porte si affacciano su stanze d’altri tempi, dentro ci sono i ricordi, le immagini ei pensieri di allora e lei si sente finalmente libera di seguirli, di andare avanti e indietro senza che il braccio di nessuno l’aiuti.<br />
                            Adesso che tutte le finestre sono chiuse, può andare a letto anche lei. La sveglia puntata sulle sei, perché vuole mettere su il sugo prima di svegliare Marco e Francesco che vanno già a scuola. La signora Luciana ha portato le uova fresche e così potrà preparare zabaione e caffè, per colazione; deve ricordarsi che Francesco ci vuole meno zucchero e prima che esca c’è da rammendargli un guanto. Pensa con allegria alle cose che ci sono sempre da fare in una casa.<br />
                            Tra le cornici dei portaritratti in fila sul comò i volti dei suoi cari la guardano, e a lei sembra di avere meritato la loro approvazione, mentre s’allunga fuori dalle coperte per spegnere l’abatjour sul comodino.<br /><br />

                        </div>
                        <div class="modal-footer">
                            Ultima Sera Dell'anno - Il lavoro editoriale,Ancona, 1988
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CHIUDI</button>
                        </div>
                    </div>
                </div>
            </div >


        )
    }
}
